### PR TITLE
fix: Fix bug in Line-Bomb and refactor item logic

### PR DESCRIPTION
**Pull request by dev-moonsc**
- Fixed Line-Bomb to work as intended.
- Fixed typos related to Ghost.
- Refactored Ghost logic

### CODE REVIEW

**Comment by smeasylife** [comment]
LGTM :)

**Comment by javadocq** [comment]
Did you miss the part where multishot is excluded if isMaxNumShot becomes true?

**Comment by dev-moonsc** [comment]
> Did you miss the part where multishot is excluded if isMaxNumShot becomes true?

It doesn't show up because it wasn't reflected in the branch I was working on. I'll manually resolve the conflict and merge it.

**Comment by javadocq** [comment]
> It doesn't show up because it wasn't reflected in the branch I was working on. I'll manually resolve the conflict and merge it.

Okay, I agree to  merge it.

**Comment by specture258** [comment]
May I know where the bug occurred?

**Comment by dev-moonsc** [comment]
> May I know where the bug occurred?

There was a bug for the following reasons and it has been fixed.

1. There was an error in the maxRow update process.

2. EnemyShipFormation's enemies are not removed at the same time as being shot. They go through the process of being removed in EnemyShipFormation.update() after being exploded. If you count without considering this process, an error occurs.

3. The process of adding Bullets to recyclable is handled in GameScreen.manageCollisions(), so parameter passing is unnecessary.

4. Int variables score and shipsDestroyed are passed as parameters and are not returned after being processed, so score and shipsDestroyed are not calculated.

---

아래의 이유로 버그가 존재했었고 현재 수정했습니다.

1. maxRow의 업데이트 과정에 오류가 있었음.

2. EnemyShipFormation의 적은 총에 맞음과 동시에 remove되지 않음. Explosion 된 뒤 EnemyShipFormation.update()에서 remove 되는 과정을 거침. 해당 과정을 고려하지 않고 카운팅할 경우 오류 발생.

3. Bullet을 recyclable에 추가하는 과정은 GameScreen.manageCollisions()에서 처리하고 있는 과정이므로 파라미터 전달이 불필요함.

4. Int 변수인 score과 shipsDestroyed를 파라미터로 전달하고 처리한 뒤 반환되지 않아 score과 shipsDestroyed가 계산되지 않음.

**Review by javadocq — APPROVED** [review]
LGTM :)

**Comment by specture258** [comment]
Yes, I understood. There was an error when I tried to complete everything in class. I should have checked it one more time. I'm sorry. It's okay to merge with the develop branch.

**Pull request merged**
